name: ci

on: [push, pull_request]

jobs: 
  ci:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: set up zig
        uses: mlugg/setup-zig@v2

      - name: build 
        run: | 
          mkdir zig-out
          zig build-exe -target=x86_64-windows -femit-bin=zig-out/transparenZ.exe
